import { useState } from "react";
import CommonInput from "./CommonInput";
import { Switch } from "@/components/ui/switch";



const CommonIdGenerator = ({ label, placeholder = 'eqwtyu' }) => {
    const [isAutoGenerated, setIsAutoGenerated] = useState(true);


    return (
        <div className="grid grid-cols-1 md:flex items-end gap-4">
            <div className="flex-1 md:max-w-[50%]">
                <CommonInput
                    label={label}
                    placeholder={placeholder}
                    disabled={isAutoGenerated}
                />
            </div>
            <div className="flex items-center gap-3 mb-2">
                <Switch
                    checked={isAutoGenerated}
                    onCheckedChange={setIsAutoGenerated}
                    className="data-[state=checked]:bg-primary"
                />
                <span className="text-[15px] font-medium text-text-bold">Auto-Generated</span>
            </div>
        </div>
    )
}

export default CommonIdGenerator;